---
- hosts: all
  tasks:
  - name: Ping test
    win_ping:
    register: ping_result
    become: true

  - debug: msg="Unable to reach endpoint"
    when: '"unreachable" in ping_result'

  - debug: msg="Unable to reach endpoint"
    when: '"ping" in ping_result'
